/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;

import Modelo.Controle;
import javax.swing.JOptionPane;

/**
 *
 * @author vilso
 */
public class frmDOIS extends javax.swing.JDialog
{
    private int acumulopontos;
    private int totalerros;
    
    private void execucao(String click)
    {
        Controle controle = new Controle(click);
        if (controle.getMensagem().equals("Pontuou"))
        {
            acumulopontos += 1;
            lblpontos.setText("Pontos: "+Integer.toString(acumulopontos)+ "/7");
            if (acumulopontos == 7)
            {
                JOptionPane.showMessageDialog(this, "Parabéns");
                System.exit(0);
            }
        }
        else
        {
            totalerros += 1;
            lblerros.setText("Erros: "+Integer.toString(totalerros) + "/3");
            if (totalerros == 3)
            {
                JOptionPane.showMessageDialog(this, "Voce perdeu");
                System.exit(0);
            }
            
        }
    }
    public frmDOIS(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jToggleButton1 = new javax.swing.JToggleButton();
        lblCaixaDeAgua = new javax.swing.JLabel();
        lblPlantas = new javax.swing.JLabel();
        lblGarrafas = new javax.swing.JLabel();
        lblRalo = new javax.swing.JLabel();
        lblPneu = new javax.swing.JLabel();
        lblLixo = new javax.swing.JLabel();
        lblCalhas = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        lblpontos = new javax.swing.JLabel();
        lblerros = new javax.swing.JLabel();
        txfTexto = new javax.swing.JTextField();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCaixaDeAgua.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        lblCaixaDeAgua.setForeground(new java.awt.Color(255, 0, 0));
        lblCaixaDeAgua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCaixaDeAgua.setToolTipText("");
        lblCaixaDeAgua.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblCaixaDeAguaMouseClicked(evt);
            }
        });
        getContentPane().add(lblCaixaDeAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 74, 200, 120));

        lblPlantas.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        lblPlantas.setForeground(new java.awt.Color(255, 0, 0));
        lblPlantas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlantas.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblPlantasMouseClicked(evt);
            }
        });
        getContentPane().add(lblPlantas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 120, 80));

        lblGarrafas.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        lblGarrafas.setForeground(new java.awt.Color(255, 0, 0));
        lblGarrafas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGarrafas.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblGarrafasMouseClicked(evt);
            }
        });
        getContentPane().add(lblGarrafas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 90, 90));

        lblRalo.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        lblRalo.setForeground(new java.awt.Color(255, 0, 0));
        lblRalo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRalo.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblRaloMouseClicked(evt);
            }
        });
        getContentPane().add(lblRalo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, 60, 50));

        lblPneu.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        lblPneu.setForeground(new java.awt.Color(255, 0, 0));
        lblPneu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPneu.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblPneuMouseClicked(evt);
            }
        });
        getContentPane().add(lblPneu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 90, 80));

        lblLixo.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        lblLixo.setForeground(new java.awt.Color(255, 0, 0));
        lblLixo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLixo.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblLixoMouseClicked(evt);
            }
        });
        getContentPane().add(lblLixo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 120, 90));

        lblCalhas.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        lblCalhas.setForeground(new java.awt.Color(255, 0, 0));
        lblCalhas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCalhas.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblCalhasMouseClicked(evt);
            }
        });
        getContentPane().add(lblCalhas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 180, 70));

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Apresentacao/erross.jpg"))); // NOI18N
        lblImagem.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblImagemMouseClicked(evt);
            }
        });
        getContentPane().add(lblImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 350, 650));

        lblpontos.setText("Pontos: 0/7");
        getContentPane().add(lblpontos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 90, 20));

        lblerros.setText("Erros: 0/3");
        getContentPane().add(lblerros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 20));

        txfTexto.setText("       Clique onde estão fazendo mal para o meio ambiente");
        txfTexto.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txfTextoActionPerformed(evt);
            }
        });
        getContentPane().add(txfTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCaixaDeAguaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblCaixaDeAguaMouseClicked
    {//GEN-HEADEREND:event_lblCaixaDeAguaMouseClicked
        if (lblCaixaDeAgua.getText() == "X")
        {
            JOptionPane.showMessageDialog(this, "Ja foi");
        }
        else
        {
            lblCaixaDeAgua.setText("X");
            execucao("Acertou");
        }
    }//GEN-LAST:event_lblCaixaDeAguaMouseClicked

    private void lblPlantasMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblPlantasMouseClicked
    {//GEN-HEADEREND:event_lblPlantasMouseClicked
        if (lblPlantas.getText() == "X")
        {
            JOptionPane.showMessageDialog(this, "Ja foi");
        }
        else
        {
            lblPlantas.setText("X");
            execucao("Acertou");
        }
    }//GEN-LAST:event_lblPlantasMouseClicked

    private void lblGarrafasMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblGarrafasMouseClicked
    {//GEN-HEADEREND:event_lblGarrafasMouseClicked
        if (lblGarrafas.getText() == "X")
        {
            JOptionPane.showMessageDialog(this, "Ja foi");
        }
        else
        {
            lblGarrafas.setText("X");
            execucao("Acertou");
        }
    }//GEN-LAST:event_lblGarrafasMouseClicked

    private void lblRaloMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblRaloMouseClicked
    {//GEN-HEADEREND:event_lblRaloMouseClicked
        if (lblRalo.getText() == "X")
        {
            JOptionPane.showMessageDialog(this, "Ja foi");
        }
        else
        {
            lblRalo.setText("X");
            execucao("Acertou");
        }
    }//GEN-LAST:event_lblRaloMouseClicked

    private void lblPneuMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblPneuMouseClicked
    {//GEN-HEADEREND:event_lblPneuMouseClicked
        if (lblPneu.getText() == "X")
        {
            JOptionPane.showMessageDialog(this, "Ja foi");
        }
        else
        {
            lblPneu.setText("X");
            execucao("Acertou");
        }
    }//GEN-LAST:event_lblPneuMouseClicked

    private void lblLixoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblLixoMouseClicked
    {//GEN-HEADEREND:event_lblLixoMouseClicked
        if (lblLixo.getText() == "X")
        {
            JOptionPane.showMessageDialog(this, "Ja foi");
        }
        else
        {
            lblLixo.setText("X");
            execucao("Acertou");
        }
    }//GEN-LAST:event_lblLixoMouseClicked

    private void lblCalhasMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblCalhasMouseClicked
    {//GEN-HEADEREND:event_lblCalhasMouseClicked
        if (lblCalhas.getText() == "X")
        {
            JOptionPane.showMessageDialog(this, "Ja foi");
        }
        else
        {
            lblCalhas.setText("X");
            execucao("Acertou");
        }
    }//GEN-LAST:event_lblCalhasMouseClicked

    private void lblImagemMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblImagemMouseClicked
    {//GEN-HEADEREND:event_lblImagemMouseClicked
       execucao("Errou");
    }//GEN-LAST:event_lblImagemMouseClicked

    private void txfTextoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txfTextoActionPerformed
    {//GEN-HEADEREND:event_txfTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfTextoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmDOIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmDOIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmDOIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmDOIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmDOIS dialog = new frmDOIS(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblCaixaDeAgua;
    private javax.swing.JLabel lblCalhas;
    private javax.swing.JLabel lblGarrafas;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblLixo;
    private javax.swing.JLabel lblPlantas;
    private javax.swing.JLabel lblPneu;
    private javax.swing.JLabel lblRalo;
    private javax.swing.JLabel lblerros;
    private javax.swing.JLabel lblpontos;
    private javax.swing.JTextField txfTexto;
    // End of variables declaration//GEN-END:variables
}
