/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;

import Modelo.Controle;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author vilso
 */
public class frmUM extends javax.swing.JDialog
{
    private int acumulopontos;
    private int totalerros;
    
    private void execucao(String click)
    {
        Controle controle = new Controle(click);
        if (controle.getMensagem().equals("Pontuou"))
        {
            acumulopontos += 1;
            lblpontos.setText("Pontos: "+Integer.toString(acumulopontos)+ "/11");
            if (acumulopontos == 11)
            {
                JOptionPane.showMessageDialog(this, "Parabéns");
                frmDOIS frmd = new frmDOIS(null, true);
                frmd.setVisible(true);
            }
        }
        else
        {
            totalerros += 1;
            lblerros.setText("Erros: "+Integer.toString(totalerros)+"/3");
            if (totalerros == 3)
            {
                JOptionPane.showMessageDialog(this, "Voce perdeu");
                System.exit(0);
            }
            
        }
    }
    public frmUM(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblFabrica = new javax.swing.JLabel();
        lblEsgoto = new javax.swing.JLabel();
        lblLixoNoRio = new javax.swing.JLabel();
        lblDesmatamento = new javax.swing.JLabel();
        lblDesperdicio = new javax.swing.JLabel();
        lblEnergia = new javax.swing.JLabel();
        lblPapel = new javax.swing.JLabel();
        lblGarrafa = new javax.swing.JLabel();
        lblPet = new javax.swing.JLabel();
        lblLata = new javax.swing.JLabel();
        lblPneu = new javax.swing.JLabel();
        lblpontos = new javax.swing.JLabel();
        lblerros = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        txfTexto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Erros");
        setFocusableWindowState(false);
        setMinimumSize(new java.awt.Dimension(370, 390));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFabrica.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        lblFabrica.setForeground(new java.awt.Color(255, 0, 0));
        lblFabrica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFabrica.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblFabricaMouseClicked(evt);
            }
        });
        getContentPane().add(lblFabrica, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 220, 50));

        lblEsgoto.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        lblEsgoto.setForeground(new java.awt.Color(255, 0, 0));
        lblEsgoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEsgoto.setToolTipText("");
        lblEsgoto.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblEsgotoMouseClicked(evt);
            }
        });
        getContentPane().add(lblEsgoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 60, 80));

        lblLixoNoRio.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        lblLixoNoRio.setForeground(new java.awt.Color(255, 0, 0));
        lblLixoNoRio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLixoNoRio.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblLixoNoRioMouseClicked(evt);
            }
        });
        getContentPane().add(lblLixoNoRio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 90, 90));

        lblDesmatamento.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        lblDesmatamento.setForeground(new java.awt.Color(255, 0, 0));
        lblDesmatamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDesmatamento.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblDesmatamentoMouseClicked(evt);
            }
        });
        getContentPane().add(lblDesmatamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 80, 80));

        lblDesperdicio.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        lblDesperdicio.setForeground(new java.awt.Color(255, 0, 0));
        lblDesperdicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDesperdicio.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblDesperdicioMouseClicked(evt);
            }
        });
        getContentPane().add(lblDesperdicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 40, 60));

        lblEnergia.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        lblEnergia.setForeground(new java.awt.Color(255, 0, 0));
        lblEnergia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnergia.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblEnergiaMouseClicked(evt);
            }
        });
        getContentPane().add(lblEnergia, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 30, 60));

        lblPapel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        lblPapel.setForeground(new java.awt.Color(255, 0, 0));
        lblPapel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblPapelMouseClicked(evt);
            }
        });
        getContentPane().add(lblPapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 40, 30));

        lblGarrafa.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        lblGarrafa.setForeground(new java.awt.Color(255, 0, 0));
        lblGarrafa.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblGarrafaMouseClicked(evt);
            }
        });
        getContentPane().add(lblGarrafa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 50, 20));

        lblPet.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        lblPet.setForeground(new java.awt.Color(255, 0, 0));
        lblPet.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblPetMouseClicked(evt);
            }
        });
        getContentPane().add(lblPet, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 60, 40));

        lblLata.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        lblLata.setForeground(new java.awt.Color(255, 0, 0));
        lblLata.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblLataMouseClicked(evt);
            }
        });
        getContentPane().add(lblLata, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 30, 40));

        lblPneu.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        lblPneu.setForeground(new java.awt.Color(255, 0, 0));
        lblPneu.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblPneuMouseClicked(evt);
            }
        });
        getContentPane().add(lblPneu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 70, 30));

        lblpontos.setText("Pontos: 0/11");
        getContentPane().add(lblpontos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 100, 20));

        lblerros.setText("Erros: 0/3");
        getContentPane().add(lblerros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 70, 20));

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Apresentacao/Erros.png"))); // NOI18N
        lblImagem.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblImagemMouseClicked(evt);
            }
        });
        getContentPane().add(lblImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 360, 300));

        txfTexto.setFont(new java.awt.Font("Segoe UI Emoji", 0, 11)); // NOI18N
        txfTexto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfTexto.setText("Clique onde estão fazendo mal para o meio ambiente");
        getContentPane().add(txfTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblImagemMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblImagemMouseClicked
    {//GEN-HEADEREND:event_lblImagemMouseClicked
        execucao("Errou");
    }//GEN-LAST:event_lblImagemMouseClicked

    private void lblFabricaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblFabricaMouseClicked
    {//GEN-HEADEREND:event_lblFabricaMouseClicked
        if (lblFabrica.getText() == "  X")
        {
            JOptionPane.showMessageDialog(this, "Ja foi");
        }
        else
        {
            lblFabrica.setText("  X");
            execucao("Acertou");
        }
    }//GEN-LAST:event_lblFabricaMouseClicked

    private void lblEsgotoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblEsgotoMouseClicked
    {//GEN-HEADEREND:event_lblEsgotoMouseClicked
        if (lblEsgoto.getText() == "X")
        {
            JOptionPane.showMessageDialog(this, "Ja foi");
        }
        else
        {
            lblEsgoto.setText("X");
            execucao("Acertou");
        }
    }//GEN-LAST:event_lblEsgotoMouseClicked

    private void lblLixoNoRioMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblLixoNoRioMouseClicked
    {//GEN-HEADEREND:event_lblLixoNoRioMouseClicked
        if (lblLixoNoRio.getText() == "X")
        {
            JOptionPane.showMessageDialog(this, "Ja foi");
        }
        else
        {
            lblLixoNoRio.setText("X");
            execucao("Acertou");
        }

    }//GEN-LAST:event_lblLixoNoRioMouseClicked

    private void lblDesmatamentoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblDesmatamentoMouseClicked
    {//GEN-HEADEREND:event_lblDesmatamentoMouseClicked
        if (lblDesmatamento.getText() == "X")
        {
            JOptionPane.showMessageDialog(this, "Ja foi");
        }
        else
        {
            lblDesmatamento.setText("X");
            execucao("Acertou");
        }

    }//GEN-LAST:event_lblDesmatamentoMouseClicked

    private void lblDesperdicioMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblDesperdicioMouseClicked
    {//GEN-HEADEREND:event_lblDesperdicioMouseClicked
        if (lblDesperdicio.getText() == "X")
        {
            JOptionPane.showMessageDialog(this, "Ja foi");
        }
        else
        {
            lblDesperdicio.setText("X");
            execucao("Acertou");
        }

    }//GEN-LAST:event_lblDesperdicioMouseClicked

    private void lblEnergiaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblEnergiaMouseClicked
    {//GEN-HEADEREND:event_lblEnergiaMouseClicked
        if (lblEnergia.getText() == "X")
        {
            JOptionPane.showMessageDialog(this, "Ja foi");
        }
        else
        {
            lblEnergia.setText("X");
            execucao("Acertou");
        }

    }//GEN-LAST:event_lblEnergiaMouseClicked

    private void lblPapelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblPapelMouseClicked
    {//GEN-HEADEREND:event_lblPapelMouseClicked
        if (lblPapel.getText() == "X")
        {
            JOptionPane.showMessageDialog(this, "Ja foi");
        }
        else
        {
            lblPapel.setText("X");
            execucao("Acertou");
        }
    }//GEN-LAST:event_lblPapelMouseClicked

    private void lblGarrafaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblGarrafaMouseClicked
    {//GEN-HEADEREND:event_lblGarrafaMouseClicked
        if (lblGarrafa.getText() == "X")
        {
            JOptionPane.showMessageDialog(this, "Ja foi");
        }
        else
        {
            lblGarrafa.setText("X");
            execucao("Acertou");
        }
    }//GEN-LAST:event_lblGarrafaMouseClicked

    private void lblPetMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblPetMouseClicked
    {//GEN-HEADEREND:event_lblPetMouseClicked
        if (lblPet.getText() == "X")
        {
            JOptionPane.showMessageDialog(this, "Ja foi");
        }
        else
        {
            lblPet.setText("X");
            execucao("Acertou");
        }
    }//GEN-LAST:event_lblPetMouseClicked

    private void lblLataMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblLataMouseClicked
    {//GEN-HEADEREND:event_lblLataMouseClicked
        if (lblLata.getText() == "X")
        {
            JOptionPane.showMessageDialog(this, "Ja foi");
        }
        else
        {
            lblLata.setText("X");
            execucao("Acertou");
        }
    }//GEN-LAST:event_lblLataMouseClicked

    private void lblPneuMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblPneuMouseClicked
    {//GEN-HEADEREND:event_lblPneuMouseClicked
        if (lblPneu.getText() == "  X")
        {
            JOptionPane.showMessageDialog(this, "Ja foi");
        }
        else
        {
            lblPneu.setText(" X");
            execucao("Acertou");
        }
    }//GEN-LAST:event_lblPneuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmUM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmUM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmUM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmUM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmUM dialog = new frmUM(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDesmatamento;
    private javax.swing.JLabel lblDesperdicio;
    private javax.swing.JLabel lblEnergia;
    private javax.swing.JLabel lblEsgoto;
    private javax.swing.JLabel lblFabrica;
    private javax.swing.JLabel lblGarrafa;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblLata;
    private javax.swing.JLabel lblLixoNoRio;
    private javax.swing.JLabel lblPapel;
    private javax.swing.JLabel lblPet;
    private javax.swing.JLabel lblPneu;
    private javax.swing.JLabel lblerros;
    private javax.swing.JLabel lblpontos;
    private javax.swing.JTextField txfTexto;
    // End of variables declaration//GEN-END:variables

    private JLabel toString(int totalerros)
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
